import '../config.dart';

/// SirenGrid Centralized Bilingual String Dictionary
/// Contains the complete set of 84 localized keys established in the locked prototype
class AppStrings {
  static const Map<String, String> ar = {
    // Brand
    "brand.name": "سايرنجريد",
    "brand.name_en": "(SirenGrid)",
    "brand.tagline": "خدمات الطوارئ والاستجابة · القاهرة",

    // Navigation
    "nav.home": "الرئيسية",
    "nav.track": "تتبع",
    "nav.account": "حسابي",
    "nav.settings": "الإعدادات",

    // Sign In
    "signin.title": "تسجيل الدخول",
    "signin.subtitle": "استخدم رقم هاتفك المسجل ورمز PIN الخاص بك.",
    "signin.phone_label": "رقم الهاتف",
    "signin.pin_label": "رمز PIN",
    "signin.submit": "تسجيل الدخول",
    "signin.preview_btn": "معاينة التطبيق (تطوير فقط)",
    "signin.forgot_pin": "هل نسيت رمز PIN؟",
    "signin.contact_center": "تواصل مع مركز التسجيل.",

    // Register (UI Only / Deferred Integration)
    "register.title": "إنشاء حساب",
    "register.subtitle": "سجل بياناتك لربط موقعك وسرعة إرسال فرق الطوارئ في نطاق مدينة نصر.",
    "register.name_label": "الاسم بالكامل",
    "register.phone_label": "رقم الهاتف",
    "register.nid_label": "الرقم القومي (14 رقم)",
    "register.pin_label": "رمز PIN للأمان (4 أرقام)",
    "register.pin_hint": "يُستخدم لتسجيل الدخول السريع وتأكيد بلاغات الطوارئ.",
    "register.submit": "إنشاء الحساب",
    "register.have_account": "لديك حساب بالفعل؟",
    "register.signin_link": "تسجيل الدخول",
    "register.danger_banner": "في حالة الخطر المباشر؟ اتصل برقم ${AppConfig.hotlinePolice} مباشرة — لا يلزم تسجيل الدخول.",

    // Home
    "home.greeting_prefix": "مساء الخير،",
    "home.greeting_sub": "ابقَ آمناً — المساعدة على بعد لمسة واحدة",
    "home.location_verified": "الموقع جاهز",
    "home.location_ready": "الموقع جاهز",
    "home.request_section": "طلب المساعدة الطارئة",
    "home.service_ambulance": "إسعاف",
    "home.service_ambulance_sub": "طوارئ طبية",
    "home.service_fire": "إطفاء",
    "home.service_fire_sub": "حريق أو خطر",
    "home.service_police": "شرطة",
    "home.service_police_sub": "أمن أو سلامة",
    "home.service_general": "طوارئ عامة",
    "home.service_general_sub": "مساعدة عاجلة أخرى",
    "home.quick_dial_title": "خطر وشيك؟ اتصل بـ ${AppConfig.hotlinePolice}",
    "home.quick_dial_sub": "خط الطوارئ القومي (مجاني)",
    "home.quick_dial_btn": "اتصل الآن",

    // Confirmation Sheet
    "confirm.title_prefix": "تأكيد طلب",
    "confirm.location_title": "مشاركة موقعك المباشر",
    "confirm.location_desc": "سيتم تحديد إحداثيات موقعك الحالية بدقة فور التأكيد",
    "confirm.explanation": "سيتم تنبيه أقرب وحدة طوارئ ومشاركة موقعك المباشر فوراً لضمان سرعة الوصول إليك.",
    "confirm.submit_ambulance": "تأكيد — طلب إسعاف",
    "confirm.submit_fire": "تأكيد — طلب إطفاء",
    "confirm.submit_police": "تأكيد — طلب شرطة",
    "confirm.submit_general": "تأكيد — طلب مساعدة عامة",
    "confirm.cancel": "إلغاء",
    "confirm.preview_blocked": "إرسال البلاغ غير متاح في وضع معاينة الواجهة.",

    // Tracking
    "tracking.preview_toggle_empty": "الحالة الفارغة",
    "tracking.preview_toggle_active": "معاينة بلاغ نشط",
    "tracking.empty_title": "لا توجد طلبات نشطة حالياً",
    "tracking.empty_desc": "عند طلب مساعدة طارئة، ستتمكن من متابعة مسار الاستجابة وحالة البلاغ مباشرة هنا.",
    "tracking.return_home": "العودة للرئيسية",
    "tracking.active_title": "تتبع الاستجابة المباشرة",
    "tracking.demo_badge": "تتبع تجريبي • بيانات افتراضية",
    "tracking.status_label": "حالة البلاغ:",
    "tracking.eta_label": "وقت الوصول المتوقع:",
    "tracking.eta_preparing": "جارٍ إعداد وقت الوصول",
    "tracking.eta_less_than_min": "أقل من دقيقة",
    "tracking.responder_unavailable": "موقع المستجيب المباشر غير متاح حالياً",
    "tracking.map_preview": "خريطة نطاق مدينة نصر",
    "tracking.view_empty_btn": "عرض الحالة الفارغة",
    "tracking.timeline_title": "مسار الاستجابة",
    "tracking.timeline_received": "تم استلام البلاغ",
    "tracking.timeline_review": "قيد مراجعة مركز العمليات",
    "tracking.timeline_assigned": "تم توجيه وحدة الاستجابة",
    "tracking.timeline_en_route": "في الطريق إلى موقعك",
    "tracking.timeline_arrived": "وصلت الوحدة للموقع",
    "tracking.ref_prefix": "رقم البلاغ:",
    "tracking.incident_prefix": "رقم الحادث:",
    "tracking.network_error": "تعذر تحديث حالة البلاغ. يرجى التحقق من الاتصال بالشبكة.",
    "tracking.retry_btn": "إعادة المحاولة",

    // Account
    "account.title": "حسابي",
    "account.verified": "تم التحقق",
    "account.address_label": "العنوان المسجل",
    "account.address_unavailable": "غير متاح حالياً",
    "account.nid_label": "الرقم القومي",
    "account.citizen_ref_label": "الرقم التعريفي للمواطن",
    "account.notifications_label": "إذن التنبيهات",
    "account.notifications_val": "لم يتم التحقق بعد",
    "account.notifications_not_checked": "لم يتم التحقق بعد",
    "account.demo_badge": "حساب تجريبي • بيانات افتراضية",
    "account.badge_simulated": "بيانات محاكاة",
    "account.badge_synthetic": "بيانات اصطناعية",
    "tracking.badge_simulated": "تتبع محاكاة • وضع تجريبي",
    "tracking.badge_synthetic": "تتبع اصطناعي • بيانات اصطناعية",
    "tracking.responder_simulated": "مركبة استجابة (محاكاة)",
    "tracking.responder_synthetic": "مركبة استجابة (بيانات اصطناعية)",
    "account.sign_out": "تسجيل الخروج",

    // Settings
    "settings.title": "الإعدادات",
    "settings.subtitle": "تخصيص الواجهة وتنبيهات شبكة SirenGrid",
    "settings.preferences_section": "تفضيلات التطبيق",
    "settings.language_label": "اللغة",
    "settings.language_desc": "اختر لغة واجهة التطبيق",
    "settings.language_pill": "اللغة: العربية",
    "settings.theme_label": "المظهر",
    "settings.theme_desc": "نمط العرض المفضل",
    "settings.theme_pill": "المظهر: فاتح",
    "settings.support_section": "الدعم والنظام",
    "settings.hotlines_label": "أرقام الطوارئ السريعة",
    "settings.police": "الشرطة",
    "settings.ambulance": "الإسعاف",
    "settings.fire": "الإطفاء",
    "settings.version_label": "إصدار التطبيق",
    "settings.version_val": "سايرنجريد ${AppConfig.appVersion} · ${AppConfig.operationsAr}",
  };

  static const Map<String, String> en = {
    // Brand
    "brand.name": "SirenGrid",
    "brand.name_en": "",
    "brand.tagline": "Emergency Response · Cairo",

    // Navigation
    "nav.home": "Home",
    "nav.track": "Track",
    "nav.account": "Account",
    "nav.settings": "Settings",

    // Sign In
    "signin.title": "Sign In",
    "signin.subtitle": "Use your registered phone number and PIN.",
    "signin.phone_label": "Phone Number",
    "signin.pin_label": "PIN",
    "signin.submit": "Sign In",
    "signin.preview_btn": "Preview App (Dev Only)",
    "signin.forgot_pin": "Forgot your PIN?",
    "signin.contact_center": "Contact your registration center.",

    // Register (UI Only / Deferred Integration)
    "register.title": "Create Account",
    "register.subtitle": "Register your details for instant emergency dispatch in Nasr City.",
    "register.name_label": "Full Name",
    "register.phone_label": "Phone Number",
    "register.nid_label": "National ID Number",
    "register.pin_label": "Create 4-Digit Security PIN",
    "register.pin_hint": "Used for fast emergency sign-in and account verification.",
    "register.submit": "Register",
    "register.have_account": "Already registered?",
    "register.signin_link": "Sign in",
    "register.danger_banner": "Immediate danger? Call ${AppConfig.hotlinePolice} directly — no account needed.",

    // Home
    "home.greeting_prefix": "Good evening,",
    "home.greeting_sub": "Stay safe — help is one tap away",
    "home.location_verified": "Location Ready",
    "home.location_ready": "Location Ready",
    "home.request_section": "Request Emergency Help",
    "home.service_ambulance": "Ambulance",
    "home.service_ambulance_sub": "Medical emergency",
    "home.service_fire": "Fire",
    "home.service_fire_sub": "Fire or hazard",
    "home.service_police": "Police",
    "home.service_police_sub": "Security or safety",
    "home.service_general": "General",
    "home.service_general_sub": "Other urgent help",
    "home.quick_dial_title": "Immediate danger? Call ${AppConfig.hotlinePolice}",
    "home.quick_dial_sub": "National Emergency Line (Toll-Free)",
    "home.quick_dial_btn": "Dial now",

    // Confirmation Sheet
    "confirm.title_prefix": "Confirm Request",
    "confirm.location_title": "Sharing your live location",
    "confirm.location_desc": "Current device GPS coordinates acquired upon confirmation",
    "confirm.explanation": "We'll alert the nearest dispatcher and share your live location so help can reach you quickly.",
    "confirm.submit_ambulance": "Confirm — Request Ambulance",
    "confirm.submit_fire": "Confirm — Request Fire",
    "confirm.submit_police": "Confirm — Request Police",
    "confirm.submit_general": "Confirm — Request General Assistance",
    "confirm.cancel": "Cancel",
    "confirm.preview_blocked": "Emergency submission is disabled in UI Preview Mode.",

    // Tracking
    "tracking.preview_toggle_empty": "Empty State",
    "tracking.preview_toggle_active": "Active Request Preview",
    "tracking.empty_title": "No active request",
    "tracking.empty_desc": "When you request emergency help, you'll track its progress live here.",
    "tracking.return_home": "Go to Home",
    "tracking.active_title": "Live Response Tracking",
    "tracking.demo_badge": "Demo Tracking • Synthetic Data",
    "tracking.status_label": "Status:",
    "tracking.eta_label": "Estimated Arrival:",
    "tracking.eta_preparing": "ETA is being prepared",
    "tracking.eta_less_than_min": "< 1 min",
    "tracking.responder_unavailable": "Live responder position is not available yet",
    "tracking.map_preview": "Nasr City Operations Map",
    "tracking.view_empty_btn": "Show Empty State",
    "tracking.timeline_title": "Response Progress",
    "tracking.timeline_received": "Request Received",
    "tracking.timeline_review": "Control Center Reviewing",
    "tracking.timeline_assigned": "Unit Assigned & Routed",
    "tracking.timeline_en_route": "En Route",
    "tracking.timeline_arrived": "Arrived at Location",
    "tracking.ref_prefix": "Ref:",
    "tracking.incident_prefix": "Incident:",
    "tracking.network_error": "Live status currently unavailable. Please verify network connection.",
    "tracking.retry_btn": "Retry",

    // Account
    "account.title": "Account",
    "account.verified": "Verified",
    "account.address_label": "Registered Address",
    "account.address_unavailable": "Unavailable",
    "account.nid_label": "National ID",
    "account.citizen_ref_label": "Citizen Reference",
    "account.notifications_label": "Notification Permission",
    "account.notifications_val": "Not checked yet",
    "account.notifications_not_checked": "Not checked yet",
    "account.demo_badge": "Demo Account • Synthetic Data",
    "account.badge_simulated": "Simulated Data",
    "account.badge_synthetic": "Synthetic Data",
    "tracking.badge_simulated": "Simulated Tracking • Simulation Mode",
    "tracking.badge_synthetic": "Synthetic Tracking • Synthetic Data",
    "tracking.responder_simulated": "Simulated Responder",
    "tracking.responder_synthetic": "Synthetic Responder",
    "account.sign_out": "Sign Out",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "System preferences & emergency configuration",
    "settings.preferences_section": "Interface & Locale",
    "settings.language_label": "Language",
    "settings.language_desc": "Choose interface language",
    "settings.language_pill": "Language: English",
    "settings.theme_label": "Appearance",
    "settings.theme_desc": "System theme preference",
    "settings.theme_pill": "Appearance: Light",
    "settings.support_section": "About & Emergency Support",
    "settings.hotlines_label": "Emergency Hotlines",
    "settings.police": "Police",
    "settings.ambulance": "Ambulance",
    "settings.fire": "Fire",
    "settings.version_label": "App Version",
    "settings.version_val": "SirenGrid ${AppConfig.appVersion} · ${AppConfig.operationsEn}",
  };

  static String get(String key, String languageCode) {
    if (languageCode == 'en') {
      return en[key] ?? ar[key] ?? key;
    }
    return ar[key] ?? key;
  }
}
